TITLE prog1.asm			;TITLE OF THE PROGRAM
DOSSEG				;START OF DOS SEGMENT
.MODEL SMALL			;MODEL OF THE PROGRAM
.STACK 0100h			;SIZE OF THE PROGRAM
.DATA				;DATA SEGMENT
.CODE				;CODE SEGMENT
	MOV AX, @DATA 	;READING/LOADING DATA SEGMENT
	MOV DS, AX		;LOAD THE DATA TO THE DS REGISTER (DATA)
	
	MOV AH, 02h		;REQUEST FOR CHARACTER DISPLAY
	MOV DL, 41h		;DL REGISTER FOR CHARACTER DISPLAY
	INT 21h			;INTERRUPT SERVICE FOR CHARACTER DISPLAY

	MOV AX, 4C00h		;END OF THE PROGRAM
	INT 21h
END